name: Deploy DAG to GCP VM

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**/*'
  pull_request:
    branches:
      - main
    paths:
      - 'dags/**/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ variables.GCP_PROJECT_ID }}

    - name: Clear remote models directory
      run: |
        gcloud compute ssh airflow-poc --zone us-central1-a --command "rm -rf /home/dwiputra_rio/airflow_project/dags"

    - name: Copy files to GCP VM
      run: |
        gcloud compute scp --recurse ./dags airflow-poc:/home/dwiputra_rio/airflow_project/dags --zone us-central1-a

    - name: Set permissions
      run: |
        gcloud compute ssh airflow-poc --zone us-central1-a --command "chmod -R u=rwx,go=rwx /home/dwiputra_rio/airflow_project/dags"
